spring.application.name=DanceCenterService
server.port=8080
logging.file.name=logs/app.log
loggin.level.root=INFO

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/dancecenter
spring.datasource.username=postgres
spring.datasource.password=R02024e1w
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

app.jwt.secret=kz7R2KFJPCmg8fQwag9Z4JHLKM9aXD84uWteCDJYHsX5MW5p84KWpBSfgSNqBPvP

spring.data.redis.host=localhost
spring.data.redis.port=6379
